version: '2'
services:
    montisolteste03-postgresql:
        container_name: montisolteste03-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/MontisolTeste03/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=MontisolTeste03
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
